# Numpy Arrays
Numpy arrays are the Python container specialised for multi-dimensional numerical calculations and data visualization. They are offered within the `numpy` module.

- They form an array of *homogeneous* (typically numerical) data
- A list of numerical types available for numpy-arrays is [here](http://docs.scipy.org/doc/numpy/user/basics.types.html)
- They consist of the data-array and information on the structure of the array (metadata on memory layout)
- Besides the array-type the `numpy`-module contains *vectorized* functions allowing *very fast* manipulation of `numpy`-arrays.

In [ ]:
import numpy as np

# numpy-array creation from a list:
a = np.array([1.0, 2.0, 3.0, 4.0])  # np.array is a type-conversion function
print(type(a))     # the type is numpy-array
print(a.dtype)     # the data-type object.
print(a.ndim)      # number of array dimensions
print(a.shape)     # shape of an array (interesting mainly for multi-dimensional arrays)
print(a.strides)   # The number of bytes fron one element to the next

## Basic Array creation

In [ ]:
import numpy as np

# many possibilities to create 
a = np.arange(0.0, 1.0, 0.1)  # array between two limits with a given distance
                              # between array elements. The array if a half-open
                              # interval!
print(a)
b = np.linspace(0.0, 1.0, 10) # array between two limits with a given number of
                              # array elements. Both limits are contained in the
                              # array
print(b)
c = np.zeros(10)              # array of 10 elements with 0 
print(c)

## Slicing operations
Array slicing for (one-dimensional) numpy arrays works exactly as for lists and other Python containers

In [ ]:
import numpy as np

a = np.arange(0, 11, 1)
print(a)
print(a[5])    # access 6th element (zero-based arrays!)
print(a[2:6])  # access third up to the sixth element
print(a[1::2]) # access every other element starting from the second
print(a[:-1])  # access all elements except the last

### Exercises
- create a numpy array of 10 zeros of 'int32' data-type.
- create an array with 10 logarithmically spaces elements between 1 and 100.
- Use your knowledge on C or Fortran to explain the result of the following cell

In [ ]:
import numpy as np

a = np.arange(0, 11, 1)
print("Array a:", a)
b = a[2:5]    # array slicing creates 'views' of an existing array!
print("Array b:", b)
b[0] = 100
print("Array b:", b)
print("Array a:", a)

c = np.arange(0, 11, 1)
print("Array c:", c)
d = c[2:5].copy()  # we create an explicit copy here!
print("Array d:", d)
d[0] = 100
print("Array d:", d)
print("Array c:", c)

## Array operations
`numpy`-arrays can be connected with mathematical operations and they behave as you would expect them to. All operations are *elementwise*!

In [ ]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)   # element-wise addition
print(x * y)   # element-wise multiplication
print(x + 2 * y)  # more complex manipulation
print(x**y)
print(y > 4)    # element-wise comparison resulting in
                # a bool-array!

application of high-performace, vectorized functions:

In [ ]:
x = np.linspace(0.0, 2.0 * np.pi, 50)
y = np.sin(x)
print(y)

**Manipulate numpy-arrays with vector operations whenever possible!** If somebody tells you that Python is about 10 times slower than C, they talk about element-wise array manipulations with loops!

In [ ]:
%%timeit
# fast vector operations
x = np.linspace(0.0, 2.0 * np.pi, 100)
y = np.sin(x)

In [ ]:
%%timeit
# C-like element-wise array manipulation
x = np.linspace(0.0, 2.0 * np.pi, 100)
y = np.zeros(len(x))

for i in range(len(x)):
    y[i] = np.sin(x[i])

### Exercise:
- Calculate the `scalar` product of two one-dimensional numpy arrays: $s=\sum_{i=1}^Na_ib_i$.

  **Hint**: The function `np.sum` calculates the sum of the elements of an array.
- Use the function `random_sample` witin the module `numpy.random` to create a numpy array $x$ of 1000 uniformly distributed random numbers within $[-1;1)$.
- Calculate the mean $\bar{x}=\frac 1N\sum_{i=1}^N x_i$ and the standard deviation
$s_x=\sqrt{\frac 1{N-1}\sum_{i=1}^N(x_i-\bar{x})^2}$ of the elements in $x$. Does the result meet your expectations?

  You can use the function `numpy.sum` **but not** the functions `numpy.mean` and `numpy.std` for this exercise!


In [ ]:
# your solutions here

## Basic plotting of numpy-Arrays
We will cover matplotlib in more detail later but we give some basic commands here for simple plots!

In [ ]:
%matplotlib inline
# The previous line is necessary that matplotlib plots
# appear within the Jupyter documents. It is sufficent to
# give it once within a document.
import numpy as np
import matplotlib.pyplot as plt

# matplotlib plots numpy-array values!
x = np.linspace(0.0, 2.0 * np.pi, 20)
y = np.sin(x)

# a simple x-y plot
plt.plot(x, y)


### Worked example and exercise
I will walk you through a very simple method to estimate derivatives of functions given at discrete points.

Write Python code to estimate the derivative $\frac{\rm d}{\rm{dx}}\sin(x)$ with $x\in[0, 2\pi]$ and plot the result. Create another plot showing the difference between your estimated derivative and the function $\cos(x)$.

In [ ]:
# your solution here

## Fancy indexing and masking
Slicing does not provide all the necessary functionality to extract sub-arrays. For instance, the application of a $\log$-function only should happen on elements larger than zero. We would therefore like to act on array elements meeting more complex conditions.

### Fancy indexing

In [ ]:
import numpy as np

x = np.arange(1, 11, 1)
print(x)
ind = [1, 2, 8] # indices of elements we would like to extract
b = x[ind]
print(b)
b[0] = 100
print(b)
print(x)

In contrast to slicing, fancy indexing **always** returns **copies** of the original array!

### Masking

In [ ]:
import numpy as np
import numpy.random as nr

x = nr.randint(-10, 10, 10)
print(x)
mask1 = (x > 0)  # mask is a bool array
y = x[mask1]     # extract the values from x where mask = True
print(y)
mask2 = (x > 0) & (x < 4)  # combined mask (and condition)
mask3 = (x < -5) | ( x > 5) # combined mask (or condition)
print(x[mask2])
print(x[mask3])

### Exercises:
- Give a Python command which multiplies all positive numbers in an integer-array with 2. Negative numbers should be unchanged. The mofification should happen in place, i.e. the original array is replaced by the new one.
- Write a Python function `my_sign` which calculates the signum function `sgn(x)` of an integer numpy-array:
  $$\text{sgn}(x)=\left\{\begin{array}{lr}-1 & x < 0 \\ 0 & x = 0 \\ 1 & x > 0\\\end{array}\right.$$
  The function should return a *new* array and leave the original one unchanged.

## Two-dimensional `numpy`-arrays
Two-dimensional arrays occur naturally as matrices, when reading data tables from a file or when creating 3D-plots. `numpy`-arrays can have any dimension though.

In [ ]:
import numpy as np

a = np.array([[1,2,3], [4, 5,6]])
print(a)
print(a.dtype)     # the data-type object.
print(a.ndim)      # number of array dimensions
print(a.shape)     # shape of an array (interesting mainly for multi-dimensional arrays)
print(a.strides)   # The number of bytes fron one element to the next

### Slicing
Slicing and element access follows the same rules as in one dimension. The two dimensions are treated differently and separated with a comma within the element access operator.

In [ ]:
import numpy as np

a = np.arange(32).reshape(4,8)  # reshape creates a view on the original array
                                # with a modified shape
print(a)
print(a[1,2])                   # access element of second row, thrid column
                                # first index = row, second index = column
print(a[1:3,2])                 # access elements in the second and third row and
                                # the third column
print(a[:,2])                   # access elements of third column    
print(a[2,:])                   # access elements of third row
print(a[1:-1,3:-1])             # access 2D-subarray

### Array operations

The application of functions and operations between arrays happen *element-by-element*. By default, there is no notion of matrices or vectors!

In [ ]:
import numpy as np

a = np.arange(4).reshape(2,2)
b = np.arange(5, 9).reshape(2,2)

print(a)
print(b)
print(a + b)
print(a * b)
print(np.sin(a))
print(a.dot(b))  # this is a matrix multiplication

Interesting are dimensionality reduction functions:

In [ ]:
import numpy as np

a = np.arange(6).reshape(3,2)

print(a)
print(np.sum(a))          # sum over all elements of the array
print(np.sum(a, axis=0))  # sum along the 'first axis' (rows)
print(np.sum(a, axis=1))# sum along the 'second axis' (columns)

### Reading simple data-tables into numpy-array
Very simple data tables in textfiles (numbers layout in columns) can be read with the `np.loadtxt` function into numpy-arrays

In [1]:
import numpy as np

a = np.loadtxt("data/slicing.txt")

print(a)

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]
 [30. 31. 32. 33. 34. 35.]
 [40. 41. 42. 43. 44. 45.]
 [50. 51. 52. 53. 54. 55.]]


### Exercise

Obtain sub-arrays indicated by different colors with one `numpy` slice-command for each sub-array.

<img src="figs/slicing.png" style="width: 400px" style="height: 400px">

In [ ]:
# Your solution here

# numpy-slicing for red sub-array

# numpy-slicing for organge sub-array

# numpy-slicing for green sub-array

# numpy-slicing for blue sub-array